export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #1a3c2e 0%, #2d4a3e 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #3c2a1a 0%, #4a3a2d 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #1a2d3c 0%, #2d3e4a 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #3c2a1e 0%, #4a3a32 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #1a2d3c 0%, #2a3d4c 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #3c3a1a 0%, #4a4832 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #3c1a3c 0%, #4a2d4a 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #1a3c2a 0%, #2d4a3a 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #2a1a3c 0%, #3a2d4a 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #3c1a1a 0%, #4a2d2d 100%)' },
];

// Alternative darker version with more contrast:
export const CARD_BG_DARK = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #0f2e21 0%, #1a3c2e 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #2e210f 0%, #3c2a1a 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #0f1e2e 0%, #1a2d3c 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #2e1a0f 0%, #3c2a1e 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #0f1e2e 0%, #1a2a3c 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #2e2c0f 0%, #3c3a1a 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #2e0f2e 0%, #3c1a3c 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #0f2e1a 0%, #1a3c2a 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #1a0f2e 0%, #2a1a3c 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #2e0f0f 0%, #3c1a1a 100%)' },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description: "Get interview questions and model answers based on your role, experience, and specific focus areas – no more generic prep.",
    icon: "🎯"
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
    icon: "⏱️"
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description: "Add personal notes to any question and pin important ones to the top – making your learning more organized.",
    icon: "📝"
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind Answers',
    description: "Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each topic.",
    icon: "🔍"
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description: "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation where you left off.",
    icon: "💾"
  },
];

// Additional dark theme specific data:
export const DARK_THEME_COLORS = {
  primary: {
    background: '#111827',
    surface: '#1f2937',
    card: '#374151',
    accent: '#f97316',
    text: {
      primary: '#f9fafb',
      secondary: '#d1d5db',
      muted: '#9ca3af'
    }
  },
  gradients: {
    primary: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    secondary: 'linear-gradient(135deg, #374151 0%, #4b5563 100%)',
    dark: 'linear-gradient(135deg, #111827 0%, #1f2937 100%)'
  }
};